### ISSUE TITLE
**Extra 1**: extender el informe técnico del A2.6 para incluir el historial de cambios hechos para el A2.8 y A2.9.

### ISSUE THREAD

**Issue by IsmaelP19** [gii-is-psg2/psg2-2122-g2-24#17]
El documento debería incluir también un pequeño informe sobre los beneficios y desventajas de usar la estrategia de ramas.

**Comment by javiercavlop** [comment]
Checked by Francisco Javier Cavero López at 11:14 - 13/3/22

**Comment by gonmarmar5** [comment]
Checked by Gonzalo Martínez Martínez at 11:14 - 13/03/2022

**Comment by IsmaelP19** [comment]
Checked by Ismael Pérez Ortiz at 11:17 -13/03/2022

**Comment by ivamorgra** [comment]
Checked by Iván Moreno Granado at 11:17 - 13/03/2022

**Comment by gabvidtev** [comment]
Checked by Gabriel Vidal Tévar at 11:19 - 13/03/2022
