### ISSUE TITLE
A2.7 Crear un informe técnico que describa la metodología de gestión de configuración seguida por el grupo

### ISSUE THREAD

**Issue by ivamorgra** [gii-is-psg2/psg2-2122-g2-24#8]
Debe llevar estándares de código, política de commits, estructura de los repositorios y las ramas por defecto, estrategia de ramas y políticas de versionado.

**Comment by ivamorgra** [comment]
Checked by Iván Moreno Granado at 19:58 - 3/3/22

**Comment by javiercavlop** [comment]
Checked by Francisco Javier Cavero López at 20:37 - 3/3/22

**Comment by gabvidtev** [comment]
Checked by Gabriel Vidal Tévar

**Comment by gonmarmar5** [comment]
Checked by Gonzalo Martínez Martínez at 20:33 - 07/03/22

**Comment by IsmaelP19** [comment]
Checked by Ismael Pérez Ortiz at 20:33  07/03/22
